# Radar-Sat: ECCC/CLDN 10-minute, 2.5-km flash-density GeoTIFFs.

broker amqps://anonymous@dd.weather.gc.ca/
topicPrefix v02.post
queueName q_${BROKER_USER}.${PROGRAM}.${CONFIG}.${HOSTNAME}

expire 12h
retry_ttl 12h
messageAgeMax 12h

instances 1
prefetch 1
inflight .
overwrite False
fileSizeMax 20M
logRotateCount 7
logRotateInterval 1d
runStateThreshold_idle 30m
runStateThreshold_lag 2m

subtopic lightning.#

mirror False
directory ${HOME}/.local/share/radar-sat/spool/eccc/lightning
acceptUnmatched False
accept .*/[0-9]{8}T[0-9]{4}Z_MSC_Lightning_2\.5km\.tif$
